[build]
  command = "npm install && cd apps/screenprinting && npm run build"
  publish = "apps/screenprinting/dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
