[build]
  base = "apps/landing"
  command = "npm install && npm run build"
  publish = "apps/landing/dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
