[build]
  base = "apps/webdesign"
  command = "npm install && npm run build"
  publish = "apps/webdesign/dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
