[build]
  base = "apps/screenprinting"
  command = "cd ../.. && npm install && cd apps/screenprinting && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
